### ISSUE TITLE
Website doesn't seem to be building

### ISSUE THREAD

**Issue by jni** [LIBREhub/napari-LatAm-workshop-2023#15]
This seems to have the old instructions...? (pre #11)

https://librehub.github.io/napari-LatAm-workshop-2023/day0/pre-requirements/to_be_installed.html

**Comment by jni** [comment]
CC @zoccoler

**Comment by MakerTobey** [comment]
I have the same impression. Very strange. the main page is not updating (I had a big mistake in the schedule - saying Tuesday instead of Wednesday and committed that many hours ago).

**Comment by MakerTobey** [comment]
<img width="1312" alt="Screenshot 2023-08-04 at 23 11 51" src="https://github.com/LIBREhub/napari-LatAm-workshop-2023/assets/14097042/cac46720-d65e-4057-8412-206669886f4b">

**Comment by MakerTobey** [comment]
how can this be fixed? I haven't had this problem before on GitHub.

**Comment by MakerTobey** [comment]
From the first broken commit: 
<img width="1353" alt="Screenshot 2023-08-04 at 23 13 38" src="https://github.com/LIBREhub/napari-LatAm-workshop-2023/assets/14097042/d6ff3ede-348c-4043-9907-ba594fd3b18f">

**Comment by MakerTobey** [comment]
P.s. I'm going to bed now and reconnect in the morning.

**Comment by MakerTobey** [comment]
thank you so much for fixing it Juan!
