### ISSUE TITLE
Environment notes for next time?

### ISSUE THREAD

**Issue by psobolewskiPhD** [LIBREhub/napari-LatAm-workshop-2023#22]
1. A lot of folks had `anaconda` already, which led to some issues with running (micro)mamba I think due to CONDA env vars and prefixes. Should add a section on this specifically—for better or worse, anaconda has been very well popularized. I think it should be possible to run micromamba in parallel, but definitely need to investigate. One option is to let those folks keep using their existing anaconda with conda-forge and lib mamba solver referencing to:
- https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge
- https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community
(this could be worth adding to the napari.org docs too, because it's a frequent thing that comes up.)

2. The single env for the whole workshop is simple, but it's *gigantic*, with >450 packages—I dare say it's anaconda-esque! It takes a while to solve, download, and install—even on a pretty new and fast computer with top-notch internet. It might be better—and also illustrate best practice—to break it up into dedicated envs for (some of) the sub tutorials? With caching and stuff it should be more manageable even if one of the tutorials does need everything.

**Comment by psobolewskiPhD** [comment]
So in case anyone nuked their anaconda and wants it back in their new (micro)mamba (CC: @MakerTobey ) you can do:
`mamba create -n anaconda -c anaconda anaconda python=3.8`
This will pull the anaconda meta package from the anaconda channel and make a new env named anaconda for you with python 3.8. You can change the python version as needed.

**Comment by MakerTobey** [comment]
great, thank you both. I incorporated this information into the installation guide.
